version: '3.8'

services:
  dia-tts-server:
    image: guerejemx/Dia-TTS-Server:latest  # Cambia esta línea con el nombre de la imagen que hayas creado en tu fork
    build:
      context: https://github.com/guerejemx/Dia-TTS-Server.git  # Reemplaza con el URL de tu fork en GitHub
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8003}:${PORT:-8003}"
    volumes:
      - ./model_cache:/app/model_cache
      - ./reference_audio:/app/reference_audio
      - ./outputs:/app/outputs
      - ./voices:/app/voices
    environment:
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      replicas: 1  # Número de réplicas en Swarm
      restart_policy:
        condition: on-failure  # Define la política de reinicio
